import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {hourEvents,defaultViewTime,daySpan,loadDaily,DAILY_STORAGE_KEY,inlineGoogle} from '../planner/daily-view.mjs';
import {COURSES,evaluate,defaultConditions,selectedResult} from '../planner/scenarios.mjs';
test('hour view includes overlapping couple and family events rather than guessing one live location',()=>{const r=evaluate('09',COURSES['09'][0],{});const slice=hourEvents(r.timeline,1050);assert.ok(slice.current.some(x=>x.stream==='부부'));assert.ok(slice.current.some(x=>x.stream==='가족'&&x.flight));assert.ok(slice.next.length);const shown=new Set([...slice.current,...slice.next,...slice.earlier,...slice.later]);assert.equal(shown.size,r.timeline.length);});
test('hour view includes all events sharing next start and respects end boundary',()=>{const events=[{name:'입국',start:820,end:910},{name:'이동',start:910,end:955},{name:'도착',start:955,end:955},{name:'체크인',start:955,end:985}];const slice=hourEvents(events,910);assert.deepEqual(slice.current.map(x=>x.name),['이동']);assert.deepEqual(slice.next.map(x=>x.name),['도착','체크인']);assert.deepEqual(slice.earlier.map(x=>x.name),['입국']);assert.deepEqual(slice.later,[]);});
test('before first and after final event show useful next or earlier plan without pretending active tracking',()=>{const events=[{start:600,end:650},{start:700,end:750}];const early=hourEvents(events,500);assert.equal(early.current.length,0);assert.equal(early.next.length,1);const late=hourEvents(events,800);assert.equal(late.current.length,0);assert.equal(late.next.length,0);assert.equal(late.earlier.length,2);});
test('time default uses selected travel date in Korea, otherwise first planned event',()=>{const events=[{start:735,end:820}];assert.equal(defaultViewTime('08',events,new Date('2026-10-08T03:25:00Z')),'12:25');assert.equal(defaultViewTime('09',events,new Date('2026-10-08T03:25:00Z')),'12:15');assert.deepEqual(daySpan([{start:100,end:110},{start:90,end:130}]),{start:90,end:130});});
test('new daily storage ignores previous automatic course choices and keeps future explicit choices',()=>{const old=JSON.stringify({version:2,day:'11',conditions:defaultConditions(),choices:{'08':{course:'park'},'11':{course:'karato'}}});const values=new Map([['fukuoka-courses-v2',old]]);const store={getItem:key=>values.get(key)||null};const fresh=loadDaily(store);assert.equal(fresh.day,'08');assert.equal(selectedResult(fresh,'08').course.id,'oldtown');const saved={version:2,day:'10',conditions:{...defaultConditions(),mealMode:'split'},choices:{'08':{course:'park'},'12':{course:'light',meal:'hakatadining'}}};values.set(DAILY_STORAGE_KEY,JSON.stringify(saved));const loaded=loadDaily(store);assert.equal(loaded.conditions.mealMode,'split');assert.equal(selectedResult(loaded,'08').course.id,'park');assert.equal(selectedResult(loaded,'12').course.id,'light');assert.equal(values.get('fukuoka-courses-v2'),old);});
test('daily pages expose working view controls and keep adjustment comparison maps collapsed behind main schedule',async()=>{for(const file of ['index.html','itinerary.html']){const html=await readFile(new URL('../'+file,import.meta.url),'utf8');assert.match(html,/날짜만 고르면, 오늘의 동선/);for(const id of ['days','day-view','hour-view','view-time','selected-timeline','reset'])assert.ok(html.includes('id="'+id+'"'));assert.ok(html.indexOf('id="selected-timeline"')<html.indexOf('<summary>다른 하루 코스'));assert.match(html,/<details class="daily-fold"><summary>일정 조정/);assert.match(html,/<details class="daily-fold" id="map-section"><summary>장소 지도/);assert.ok(!html.includes('id="anchors"'));assert.ok(!html.includes('jumpnav'));assert.ok(!html.includes('category-icon'));}});

test('actual inline meal preview includes Google scope caveats below ratings for facilities individual stores and search alternatives',async()=>{const {DINING_DETAILS}=await import('../planner/dining-details.mjs');const actual=DINING_DETAILS.hakatadining.google;assert.ok(actual.rating!=null&&actual.note);const html=inlineGoogle(actual);assert.ok(html.includes(actual.note));assert.ok(html.indexOf(actual.note)>html.indexOf('★'));for(const scope of ['개별 점포','시설 전체','지역 검색']){const preview=inlineGoogle({rating:scope==='지역 검색'?null:4,count:100,scope,note:'해당 범위의 평점입니다 <확인>',checked:'2026-10-07'});assert.match(preview,/google-note/);assert.match(preview,/해당 범위의 평점입니다 &lt;확인&gt;/);}const app=await readFile(new URL('../planner/scenarios-app.mjs',import.meta.url),'utf8');assert.ok(app.includes('${inlineGoogle(g)}'));});
