import test from 'node:test';import assert from 'node:assert/strict';
import {mealPolicy} from '../planner/meal-policy.mjs';
import {evaluate,COURSES,conditionInput,recommend,loadV2,selectedResult} from '../planner/scenarios.mjs';
import {plan,normalize,readSaved,assess,lookup} from '../planner/engine.mjs';
const result=(day,course,mode,meal)=>evaluate(day,COURSES[day].find(x=>x.id===course),{mealMode:mode},meal);
test('concurrent same-restaurant meals complete together rather than two sequential rounds',()=>{const r=result('12','lunch','split','hanamidori');assert.equal(r.feasible,true);assert.equal(r.finish,895);const meals=r.timeline.filter(x=>x.meal);assert.equal(meals.length,1);assert.equal(meals[0].end-meals[0].start,70);assert.equal(meals[0].mealPolicy.roundQueue,30);assert.match(meals[0].detail,/가장 늦게 마친 팀/);assert.equal(result('12','lunch','together','hanamidori').finish,915);});
test('long course meal is never shortened by split seating',()=>{assert.equal(mealPolicy({family:true,mode:'split',duration:110}).roundDuration,110);assert.equal(mealPolicy({family:true,mode:'together',duration:110}).roundDuration,110);});
test('relay includes both meals both queues and handoff before next travel',()=>{const r=result('10','harbor','relay','curry');const meals=r.timeline.filter(x=>x.meal);assert.equal(meals.length,2);assert.deepEqual(meals.map(x=>x.end-x.start),[70,70]);const queues=r.timeline.filter(x=>x.name==='가족 단체 식당 대기 가정');assert.deepEqual(queues.map(x=>x.end-x.start),[30,30]);const exchange=r.timeline.find(x=>x.name==='유아·짐 돌봄 교대');assert.equal(exchange.end-exchange.start,10);const next=r.timeline.find(x=>x.from?.id==='curry');assert.ok(next.start>=meals[1].end+25);assert.equal(meals[1].end-queues[0].start,210);assert.ok(r.timeline.find(x=>x.name==='KF1 체크인').start>=960);});
test('airport hard deadline includes all teams; narrow split meal is not recommended first',()=>{const split=result('12','lunch','split','unagi');assert.equal(split.finish,895);assert.equal(split.feasible,true);const best=recommend('12',{mealMode:'split'});assert.equal(best.meal,'hakatadining');assert.ok(900-best.finish>=15);const relay=result('12','lunch','relay','unagi');assert.equal(relay.feasible,false);assert.equal(relay.finish,1005);assert.match(relay.problems.join(),/15시/);assert.equal(recommend('12',{mealMode:'relay'}).course.id,'direct');});
test('extra queue turns narrow split plan infeasible and falls back',()=>{const r=evaluate('12',COURSES['12'][0],{mealMode:'split',mealWait:10},'unagi');assert.equal(r.finish,905);assert.equal(r.feasible,false);const s={conditions:{mealMode:'split',mealWait:10},choices:{'12':{course:'lunch',meal:'unagi'}}};assert.equal(selectedResult(s,'12').meal,'hakatadining');});
test('couple meals and mandatory admission anchors are unaffected by family seating modes',()=>{for(const d of ['08','09'])for(const c of COURSES[d]){const baseline=evaluate(d,c,{});for(const mode of ['split','relay']){const r=evaluate(d,c,{mealMode:mode});assert.equal(r.finish,baseline.finish);assert.deepEqual(r.timeline.map(x=>[x.name,x.start,x.end]),baseline.timeline.map(x=>[x.name,x.start,x.end]));}}});
test('market lunch repeats only for intentional relay and has no extra restaurant lunch',()=>{const together=result('11','karato','together');assert.equal(together.timeline.filter(x=>x.name.includes('점심 포함')).length,1);const relay=result('11','karato','relay');assert.equal(relay.timeline.filter(x=>x.name.includes('점심 포함')).length,2);assert.equal(relay.timeline.filter(x=>x.meal).length,0);assert.equal(relay.finish-together.finish,120);assert.equal(relay.timeline.filter(x=>x.name==='시장 대기·자리 확보 가정').length,2);});
test('facility relay counts two full meals and one handoff with one rest buffer',()=>{const r=result('12','lunch','relay','hakatadining');const meals=r.timeline.filter(x=>x.meal);assert.equal(meals.length,2);assert.equal(meals[1].end-meals[0].start,150);assert.equal(r.timeline.filter(x=>x.name==='이동 준비·휴식 여유').length,1);assert.equal(r.feasible,false);});
test('manual and curated engines share complete meal allowance and airport result',()=>{for(const mode of ['together','split','relay']){const s=normalize({preset:'12',mealMode:mode});const manual=assess(s,lookup('unagi'),lookup('kf1'),600,900);const curated=result('12','lunch',mode,'unagi');assert.equal(manual.eta,curated.finish);assert.equal(manual.feasible,curated.feasible);assert.equal(manual.policy.total,mealPolicy({family:true,mode,duration:70}).total);}});
test('old persisted choices default together while new valid modes survive; corruption defaults safely',()=>{const legacy={version:2,day:'12',choices:{'12':{course:'light',meal:'hakatadining'}},conditions:{rain:false,relaxed:false,mode:'transit',delay:0,mealWait:0}};const old=loadV2({getItem:()=>JSON.stringify(legacy)});assert.equal(old.conditions.mealMode,'together');assert.equal(old.choices['12'].course,'light');const fresh=loadV2({getItem:()=>JSON.stringify({...legacy,conditions:{...legacy.conditions,mealMode:'split'}})});assert.equal(fresh.conditions.mealMode,'split');assert.equal(loadV2({getItem:()=>JSON.stringify({...legacy,conditions:{...legacy.conditions,mealMode:'garbage'}})}).conditions.mealMode,'together');assert.equal(normalize({preset:'11'}).mealMode,'together');assert.equal(readSaved({getItem:()=>JSON.stringify({...normalize({preset:'11'}),mealMode:'split'})}).mealMode,'split');assert.equal(readSaved({getItem:()=>'{"mealMode":"garbage"}'}).mealMode,'together');});
test('manual condition changes remove relay-infeasible selected meals',()=>{const base={...normalize({preset:'12'}),mealMode:'split',selected:['unagi']};assert.equal(plan(base).state.selected.length,1);const changed=plan({...base,mealMode:'relay'});assert.equal(changed.state.selected.length,0);assert.match(changed.removed[0].reason,/마감 초과/);});

test('UI condition conversion preserves all seating enum strings through saved reload and calculation',()=>{for(const mode of ['together','split','relay']){const parsed=conditionInput('mealMode',mode);assert.equal(parsed,mode);assert.equal(typeof parsed,'string');const raw={version:2,day:'12',choices:{'12':{course:'lunch',meal:'unagi'}},conditions:{rain:false,relaxed:false,mode:'transit',delay:0,mealWait:0,mealMode:parsed}};const restored=loadV2({getItem:()=>JSON.stringify(raw)});assert.equal(restored.conditions.mealMode,mode);const r=evaluate('12',COURSES['12'][0],restored.conditions,'unagi');assert.equal(r.finish,{together:915,split:895,relay:1005}[mode]);assert.ok(!r.problems.some(x=>x.includes('조건을 확인')));}assert.equal(conditionInput('delay','30'),30);assert.equal(conditionInput('mealWait','15'),15);assert.equal(conditionInput('mealMode','bad'),'together');assert.equal(conditionInput('rain',false),false);});
