import test from 'node:test';import assert from 'node:assert/strict';
import {DAYS,COURSES,cases,evaluate,fallback,recommend,loadV2,selectedResult} from '../planner/scenarios.mjs';
const chosen=(d,id,c={},m)=>evaluate(d,COURSES[d].find(x=>x.id===id),c,m);
test('arrival, admission and hotel checkin always precede first day tourism',()=>{for(const r of cases('08',{})){assert.equal(r.feasible,true);const flight=r.timeline.find(x=>x.name==='인천 출발 → 후쿠오카 도착');assert.equal(flight.start,735);assert.equal(flight.end,820);const admission=r.timeline.find(x=>x.name==='입국·수하물 여유');assert.equal(admission.end,910);const checkin=r.timeline.find(x=>x.name==='GRAND BASE 체크인');assert.equal(checkin.start,955);assert.equal(checkin.end,985);const first=r.timeline.find(x=>!x.mandatory&&x.place);assert.ok(first.start>=checkin.end);assert.ok(r.finish<=1260);}});
test('day9 separate couple and family streams without forced airport pickup',()=>{const r=chosen('09','sea');assert.equal(r.feasible,true);assert.ok(r.timeline.every((x,i,a)=>i===0||a[i-1].start<=x.start));const couple=r.timeline.find(x=>x.name.includes('→ GRAND BASE')&&x.stream==='부부');assert.equal(couple.end,1105);assert.ok(!r.timeline.some(x=>x.to?.id==='airport'&&!x.flight));const flight=r.timeline.find(x=>x.name==='가족: 인천 출발 → 후쿠오카 도착');assert.equal(flight.start,1020);assert.equal(flight.end,1110);const family=r.timeline.find(x=>x.name==='가족: 공항 → GRAND BASE');assert.equal(family.start,1185);assert.equal(family.end,1230);const checkin=r.timeline.find(x=>x.name.includes('가족 합류 후'));assert.equal(checkin.end,1260);});
test('day10 luggage cannot be dropped before13 and checkin never before16',()=>{for(const r of cases('10',{})){assert.equal(r.feasible,true);const luggage=r.timeline.find(x=>x.name==='KF1 짐 맡기기');if(luggage)assert.equal(luggage.start,780);const checkin=r.timeline.find(x=>x.name==='KF1 체크인');assert.ok(checkin.start>=960);assert.equal(checkin.end-checkin.start,30);if(r.course.carry)assert.equal(luggage,undefined);}});
test('day12 default lunch arrives14:25 and mandatory flight remains18',()=>{const r=chosen('12','lunch');assert.equal(r.feasible,true);assert.equal(r.finish,865);assert.equal(r.timeline.find(x=>x.name==='KF1 체크아웃·짐 동반 출발').start,600);assert.equal(r.timeline.find(x=>x.name==='후쿠오카 출발 → 인천 도착').start,1080);assert.equal(r.timeline.find(x=>x.name==='후쿠오카 출발 → 인천 도착').end,1185);});
test('all selectable alternatives preserve international arrival and hotel hard deadline',()=>{for(const mode of ['transit','driving'])for(const rain of [false,true])for(const d of DAYS){for(const r of [...cases(d,{mode,rain}),fallback(d,{mode,rain})].filter(x=>x.feasible)){if(d==='12')assert.ok(r.finish<=900);if(d==='09')assert.ok(r.finish<=1320);if(d==='08')assert.ok(r.finish<=1260);}}});
test('delays reject complete courses and choose mandatory direct fallback without bypass',()=>{const r=recommend('12',{delay:120});assert.equal(r.course.id,'direct');assert.equal(r.feasible,true);assert.equal(r.finish,890);assert.ok(cases('12',{delay:120}).every(x=>!x.feasible));const late=fallback('12',{delay:180});assert.equal(late.feasible,false);assert.match(late.problems.join(),/15시/);assert.ok(late.timeline.some(x=>x.name==='국제선 터미널 도착'));});
test('course meal substitution is restricted to matching geography',()=>{const r=chosen('10','harbor',{},'bearfruits');assert.equal(r.meal,'bearfruits');assert.ok(r.timeline.some(x=>x.place?.id==='bearfruits'));const bad=chosen('10','harbor',{},'unagi');assert.equal(bad.meal,'curry');assert.ok(!bad.timeline.some(x=>x.place?.id==='unagi'));const lunch=chosen('12','lunch',{},'hakatadining');assert.equal(lunch.finish,865);});
test('Sunday market includes lunch once; no invented second meal',()=>{const r=chosen('11','karato');assert.equal(r.timeline.filter(x=>x.name.includes('점심 포함')).length,1);assert.equal(r.timeline.filter(x=>x.meal).length,0);});
test('relaxed conditions favor indoor short routes while legacy weather is ignored',()=>{for(const day of DAYS){const r=recommend(day,{rain:true,relaxed:true});assert.equal(r.feasible,true);assert.ok(!r.course.outdoor);assert.ok(r.timeline.filter(x=>x.place&&!x.mandatory).every(x=>x.place.stroller!==false));}assert.equal(recommend('08',{relaxed:true}).course.id,'canal');assert.equal(recommend('11',{rain:true}).course.id,'karato');});
test('v2 persistence ignores legacy/manual and corrupt input while preserving separate days',()=>{assert.equal(loadV2({getItem:()=>'{bad'}).day,'08');assert.equal(loadV2({getItem:()=>JSON.stringify({preset:'12',selected:['retro']})}).day,'08');const s=loadV2({getItem:()=>JSON.stringify({version:2,day:'10',conditions:{rain:false,relaxed:false,mode:'transit',delay:0},choices:{'08':{course:'oldtown',meal:'unagi'},'11':{course:'kokura',meal:'katsu'}}})});assert.equal(selectedResult(s,'08').course.id,'oldtown');assert.equal(selectedResult(s,'11').course.id,'kokura');assert.equal(selectedResult({...s,conditions:{...s.conditions,rain:true}},'11').course.id,'kokura');});
test('family arrival fixed baseline still contains evening meal decision caveat',()=>{const r=fallback('09',{});assert.ok(r.timeline.some(x=>x.conditional&&x.detail.includes('영업')));assert.equal(r.finish,1260);});

test('family curry alternatives include conservative90minute meal and30minute queue',()=>{for(const id of ['curry','bearfruits']){const r=chosen('10','harbor',{},id);assert.equal(r.feasible,true);const meal=r.timeline.find(x=>x.meal);assert.equal(meal.end-meal.start,90);const queue=r.timeline.find(x=>x.name==='가족 단체 식당 대기 가정');assert.equal(queue.end-queue.start,30);assert.ok(r.timeline.find(x=>x.place?.id==='retro').end<meal.start);}});
test('actual Hanamidori lunch opening and dinner-only Rakutenchi are respected',()=>{const lunch=chosen('09','rain',{},'hanamidori');const meal=lunch.timeline.find(x=>x.meal);assert.ok(meal.start>=690);assert.ok(meal.start<=840);assert.ok(meal.end<=900);const dinner=chosen('08','oldtown',{},'motsu');assert.ok(dinner.timeline.find(x=>x.meal).start>=1020);});
test('extra restaurant waiting cannot bypass15airport deadline and chooses direct alternative',()=>{const r=recommend('12',{mealWait:60});assert.equal(r.course.id,'direct');assert.equal(r.feasible,true);const waiting=chosen('12','lunch',{mealWait:60});assert.equal(waiting.feasible,false);assert.ok(waiting.finish>900);const s={conditions:{rain:false,mode:'transit',relaxed:false,delay:0,mealWait:60},choices:{'12':{course:'lunch',meal:'hanamidori'}}};assert.equal(selectedResult(s,'12').course.id,'direct');});
test('evidence separates official facts review samples and inference without claiming consensus',async()=>{const {evidenceHTML,EVIDENCE}=await import('../planner/evidence.mjs');const html=evidenceHTML(['unagi','curry','hakatadining']);assert.match(html,/2026-10-07/);assert.match(html,/일부 후기 표본/);assert.match(html,/공식 사실/);assert.match(html,/Google 확인 후기 표본/);assert.match(html,/커뮤니티/);assert.match(html,/우리 가족에 대한 판단/);assert.match(html,/리뷰 종합 전/);assert.match(EVIDENCE.hanamidori.google,/본문은 보이지 않아/);assert.match(EVIDENCE.motsu.google,/24,121/);});

test('Ohori and Dazaifu lunch defaults use researched named restaurants with own timing',()=>{const sea=chosen('09','sea');assert.equal(sea.meal,'royalcafe');const royal=sea.timeline.find(x=>x.meal);assert.ok(royal.start>=660&&royal.end<=900);const dazaifu=chosen('09','dazaifu');assert.equal(dazaifu.meal,'shizenan');assert.equal(dazaifu.feasible,true);const tofu=dazaifu.timeline.find(x=>x.meal);assert.equal(tofu.end-tofu.start,110);assert.ok(tofu.start<=930&&tofu.end<=990);});
test('museum official links stay associated with correct museum',async()=>{const {resolve}=await import('../planner/scenarios.mjs');assert.equal(resolve('museum').source,'https://www.kyuhaku.jp/');assert.equal(resolve('kanmonmuseum').source,'https://www.crossroadfukuoka.jp/spot/13211');});

test('family sitdown alternatives require90meal30queue and cannot claim airport feasibility',()=>{for(const id of ['hanamidori','unagi']){const r=chosen('12','lunch',{},id);assert.equal(r.feasible,false);assert.equal(r.finish,915);const meal=r.timeline.find(x=>x.meal);assert.equal(meal.end-meal.start,90);const queue=r.timeline.find(x=>x.name==='가족 단체 식당 대기 가정');assert.equal(queue.end-queue.start,30);}const r=chosen('11','kokura',{},'katsu');assert.equal(r.timeline.find(x=>x.meal).end-r.timeline.find(x=>x.meal).start,90);});
