import test from 'node:test';import assert from 'node:assert/strict';
import {COURSES,DAYS,evaluate,resolve,loadV2,defaultConditions,recommend} from '../planner/scenarios.mjs';
import {detailedTimeline,timelinePins,embedMap} from '../planner/timeline-view.mjs';
import {transportGuide} from '../planner/transport.mjs';
import {normalize,plan} from '../planner/engine.mjs';
const ev=d=>evaluate(d,COURSES[d][0],{});
test('all course timelines remain chronological and every travel leg has endpoints and guide metadata',()=>{for(const d of DAYS)for(const c of COURSES[d])for(const mode of ['transit','driving']){const r=evaluate(d,c,{mode});const detailed=detailedTimeline(r);assert.equal(detailed.length,r.timeline.length);for(let i=0;i<detailed.length;i++){const t=detailed[i];if(i)assert.ok(t.start>=detailed[i-1].start);assert.ok(t.end>=t.start);if(t.from){assert.ok(t.from.query&&t.to.query);assert.equal(t.end-t.start,t.travel);if(!t.flight){assert.ok(t.guide.label);assert.ok(t.guide.steps.length);assert.ok(Array.isArray(t.guide.waypoints));assert.ok(t.guide.sources.every(x=>x.url.startsWith('https://')));}}}}});
test('repeat visits remain distinct numbered pins and transfer pins have no fictional departure time',()=>{const pins=timelinePins(detailedTimeline(ev('08')));assert.ok(pins.filter(p=>p.id==='hotel').length>=2);assert.ok(pins.some(p=>p.id==='icn'));assert.ok(pins.some(p=>p.id==='airport'));const domestic=pins.find(p=>p.id==='domestic');assert.ok(domestic.transfer);assert.deepEqual(domestic.range,[910,955]);assert.ok(pins.some(p=>p.id==='nakasu'));assert.ok(pins.some(p=>p.id==='gofuku'));assert.deepEqual(pins.map(p=>p.number),pins.map((_,i)=>i+1));assert.ok(pins.every(p=>p.url.startsWith('https://www.google.com/maps/search/')));});
test('day9 pin streams stay separate in chronological display',()=>{const pins=timelinePins(detailedTimeline(ev('09')));assert.ok(pins.some(p=>p.id==='icn'&&p.stream==='가족'));assert.ok(pins.some(p=>p.id==='hotel'&&p.stream==='부부'));assert.ok(!pins.some(p=>p.id==='airport'&&p.stream==='부부'));assert.ok(pins.every((p,i)=>!i||p.at>=pins[i-1].at));});
test('selected place embeds exact encoded query without API keys or route mixing',()=>{const p=resolve('unagi');const u=new URL(embedMap(p));assert.equal(u.hostname,'maps.google.com');assert.equal(u.searchParams.get('q'),'吉塚うなぎ屋');assert.equal(u.searchParams.get('output'),'embed');assert.ok(!u.searchParams.has('key'));});
test('old rain settings never hide outdoor options or overwrite separate course choices',()=>{const saved={version:2,day:'11',choices:{'11':{course:'karato'}},conditions:{...defaultConditions(),rain:true}};const s=loadV2({getItem:()=>JSON.stringify(saved)});assert.equal(s.conditions.rain,false);assert.equal(recommend('11',{rain:true}).course.id,recommend('11',{}).course.id);const manual=normalize({preset:'11',rain:true});assert.equal(manual.rain,false);assert.equal(plan(manual).choices.find(x=>x.stop.id==='retro').feasible,true);});
test('airport to hotel guide preserves shuttle then subway transfer and official sources',()=>{const g=transportGuide(resolve('airport'),resolve('hotel'),'transit');const text=g.steps.join(' ');assert.match(text,/5번/);assert.ok(text.indexOf('국내선')<text.indexOf('나카스카와바타'));assert.ok(text.indexOf('나카스카와바타')<text.indexOf('고후쿠마치'));assert.deepEqual(g.waypoints.map(x=>x.id),['domestic','nakasu','gofuku']);assert.ok(g.sources.some(x=>x.url.includes('fukuoka-airport.jp')));assert.match(g.note,/실제 열차/);});
test('return airport guide reaches international terminal after domestic terminal shuttle',()=>{const g=transportGuide(resolve('hakatadining'),resolve('airport'),'transit');assert.match(g.steps.join(' '),/국내선.*1번.*무료 셔틀.*국제선/);assert.ok(g.waypoints.some(x=>x.id==='domestic'));});
test('KF1 to market requires JR then ferry and reverse returns through both piers',()=>{const out=transportGuide(resolve('kf1'),resolve('market'),'transit');const ids=out.waypoints.map(x=>x.id);assert.ok(ids.indexOf('moji-station')<ids.indexOf('moji-pier'));assert.ok(ids.indexOf('moji-pier')<ids.indexOf('karato-pier'));assert.match(out.steps.join(' '),/JR.*연락선/);const back=transportGuide(resolve('market'),resolve('kf1'),'transit');const b=back.waypoints.map(x=>x.id);assert.ok(b.indexOf('karato-pier')<b.indexOf('moji-pier'));assert.ok(b.indexOf('moji-pier')<b.indexOf('moji-station'));assert.ok(back.sources.some(x=>x.url.includes('kanmon-kisen')));});
test('vehicle guides contain no subway proposal or private party count and preserve approximate KF1 warning',()=>{const g=transportGuide(resolve('airport'),resolve('hotel'),'driving');assert.ok(!g.steps.join(' ').includes('지하철'));assert.match(g.steps.join(' '),/가족.*나눠/);assert.ok(!g.steps.join(' ').includes('6명'));const k=transportGuide(resolve('hotel'),resolve('kf1'),'driving');assert.match(k.steps.join(' '),/근사 위치/);});
test('transport explanations never change the45minute mandatory airport allowance',()=>{const r=ev('08');const leg=detailedTimeline(r).find(x=>x.from?.id==='airport'&&!x.flight);assert.equal(leg.travel,45);assert.equal(leg.start,910);assert.equal(leg.end,955);assert.equal(r.timeline.find(x=>x.name==='GRAND BASE 체크인').start,955);});

test('manual airport and KF1 hub connection includes international shuttle JR and Moji pins in both directions',()=>{for(const [from,to] of [[resolve('airport'),resolve('kf1')],[resolve('kf1'),resolve('airport')]]){const g=transportGuide(from,to,'transit');const text=g.steps.join(' ');assert.match(text,/셔틀/);assert.match(text,/JR/);assert.match(text,/신칸센/);assert.match(text,/택시/);assert.ok(g.waypoints.some(x=>x.id==='domestic'));assert.ok(g.waypoints.some(x=>x.id==='hakata'));assert.ok(g.waypoints.some(x=>x.id==='kokura'));assert.ok(g.waypoints.some(x=>x.id==='moji-station'));assert.ok(g.sources.some(x=>x.url.includes('fukuoka-airport.jp')));assert.ok(g.sources.some(x=>x.url.includes('jrkyushu.co.jp')));assert.equal(new Set(g.sources.map(x=>x.url)).size,g.sources.length);assert.ok(g.waypoints.every((p,i)=>!i||p.id!==g.waypoints[i-1].id));}});

test('unverified KF1 nature routes do not invent Mojiko walking connections or station pins',()=>{for(const id of ['sarakuraview','plateau','shiranoegarden','itoshima']){for(const [from,to] of [[resolve('kf1'),resolve(id)],[resolve(id),resolve('kf1')]]){const g=transportGuide(from,to,'transit');assert.match(g.label,/실제 주소 확인/);assert.match(g.steps.join(' '),/근사 위치/);assert.match(g.steps.join(' '),/확인/);assert.ok(!g.steps.join(' ').includes('모지코역'));assert.deepEqual(g.waypoints,[]);assert.ok(Array.isArray(g.steps));assert.ok(g.steps.length>0);}}});
test('manual actually selectable Sarakura leg uses unverified connection fallback in both directions',()=>{const r=plan({...normalize({preset:'11'}),stroller:false,selected:['sarakuraview']});assert.equal(r.error,null);assert.deepEqual(r.state.selected,['sarakuraview']);assert.equal(r.timeline[0].from.id,'kf1');const outbound=transportGuide(r.timeline[0].from,r.timeline[0].stop,r.state.mode);const inbound=transportGuide(r.from,resolve(r.state.destination),r.state.mode);for(const g of [outbound,inbound]){assert.equal(typeof g,'object');assert.match(g.label,/실제 주소 확인/);assert.deepEqual(g.waypoints,[]);assert.ok(!g.steps.join(' ').includes('모지코역'));}assert.ok(r.eta<=r.end);});
test('verified Kokura and Mojiko KF1 connections retain JR station pins in both directions',()=>{for(const id of ['castle','retro'])for(const [from,to] of [[resolve('kf1'),resolve(id)],[resolve(id),resolve('kf1')]]){const g=transportGuide(from,to,'transit');assert.match(g.steps.join(' '),/JR/);assert.ok(g.waypoints.some(p=>p.id==='moji-station'));assert.ok(g.waypoints.some(p=>p.id===(id==='castle'?'kokura':'mojiko')));assert.ok(g.sources.some(s=>s.url.includes('jrkyushu.co.jp')));}});
