import {MEAL_MODES} from './meal-policy.mjs?v=20261007-meal-modes-2';
import {locations,presets,zones} from './data.mjs';
import {readSaved,saveState,plan,normalize,clock,maps,route,lookup} from './engine.mjs?v=20261007-meal-modes-2';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage;try{storage=window.localStorage;}catch{storage=null;}
let state=readSaved(storage);
const q=new URLSearchParams(location.search);const focus=Object.hasOwn(zones,q.get('zone'))?q.get('zone'):null;
for(const field of ['origin','destination'])$(field).innerHTML=locations.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');
const fields=['origin','departure','destination','deadline','mode','party','mealMode','rain','stroller'];
function fill(){for(const f of fields)if(['rain','stroller'].includes(f))$(f).checked=state[f];else $(f).value=state[f];}
function card(r){const s=r.stop;return `<article class="card"><span class="fine">${esc(zones[s.zone])} · ${s.kind==='restaurant'?(s.facility?'시설·검색 선택지':'식당'):(s.outdoor?'야외':'실내 위주')}</span><h3>${esc(s.name)}</h3><p>${s.cuisine?'<b>'+esc(s.cuisine)+'</b> · ':''}${esc(s.note)}</p><div class="meta"><p>이동 ${r.incoming}분 → ${clock(r.visit)} 방문 · 체류 ${r.stay}분</p><p>휴식·환승 ${r.buffer}분${r.wait?' · 시작 전 대기 '+r.wait+'분':''} + 목적지 이동 ${r.outgoing}분</p><p><b>목적지 ${clock(r.eta)} · 마감까지 ${r.remaining}분 여유</b></p></div>${r.policy?'<p class="fine">'+esc(r.policy.label)+' · '+esc(r.policy.explanation)+(r.policy.rounds===2?' · 두 팀 식사·대기·교대 합계 '+r.policy.total+'분':'')+'</p>':''}<p class="fine">${s.id==='railway'||s.id==='market'?'운영·개최일 확인 필요':'영업 확인 필요 · 표시 시간은 방문 계획 가정'}</p><div class="links"><a href="${maps(s)}" target="_blank" rel="noopener">장소 지도</a><a href="${route(current.from,s,state.mode)}" target="_blank" rel="noopener">가는 경로</a><a href="${esc(s.source)}" target="_blank" rel="noopener">공식 안내</a></div><button type="button" data-add="${s.id}">일정에 더하기</button></article>`;}
let current;
function render(){current=plan(state);$('presets').innerHTML=['08','09','09family','10','11','12'].map(k=>`<button type="button" data-preset="${k}" class="${k===state.preset?'active':''}" aria-pressed="${k===state.preset}">${k==='09family'?'10/09 가족 도착':'10/'+k}</button>`).join('');$('daynote').textContent=presets[state.preset].note+(focus?' '+zones[focus]+' 후보를 먼저 정렬했습니다. 출발·최종 목적지 조건은 위 설정 그대로입니다.':'');
 if(current.state){state=current.state;fill();}
 $('feedback').innerHTML=current.error?`<p class="error">${esc(current.error)}</p>`:'';
 if(!current.choices){for(const id of ['summary','attractions','restaurants','timeline','excluded'])$(id).innerHTML='';return;}
 $('meal-heading').textContent=current.hasTourist?'02 · 지금 동선 주변 식사':'02 · 이동 중 식사 선택지';
 $('meal-note').textContent=current.hasTourist?'관광을 선택하면 마지막 장소와 같은 지역(구즈하에서는 인접 모지코)의 식사로 좁힙니다. 식사 방식별 체류·대기·휴식 여유 포함. 영업·자리 확인 필요.':'관광 선택 전에는 현재 지역·목적지·이동 경로의 식사를 표시합니다. 식사만 먼저 선택해도 됩니다. 식사 방식별 체류·대기·휴식 여유 포함. 영업·자리 확인 필요.';
 if(current.removed.length)$('feedback').innerHTML+=`<p class="removed">조건 변경으로 선택 해제: ${current.removed.map(x=>esc(lookup(x.id).name)+' ('+esc(x.reason)+')').join(', ')}</p>`;
 $('summary').innerHTML=`<div class="summary"><span class="fine">${state.date} · 실제 계산 출발 ${clock(current.start)} / 도착 한계 ${clock(current.end)}</span><p><strong>${Number.isFinite(current.remaining)?current.remaining+'분 여유':'이동 방식 확인'}</strong></p><p class="fine">${current.timeline.length}곳 선택 · ${Number.isFinite(current.eta)?'현재 일정 목적지 도착 '+clock(current.eta):'지역 간 도보 이동 불가'}</p>${state.preset==='09family'?'<p class="fine">먼저 숙소 체크인. 저녁 식사는 체크인 후 근처에서 영업·마감 시간을 확인하세요.</p>':''}${!current.timeline.length&&current.remaining<95?'<p class="fine">직접 이동이 대부분의 시간을 사용합니다. 관광·식사까지 원하면 출발 시간을 앞당겨보세요.</p>':''}</div>`;
 for(const [id,kind] of [['attractions','attraction'],['restaurants','restaurant']]){const list=current.error?[]:current.choices.filter(r=>r.feasible&&r.stop.kind===kind).sort((a,b)=>((b.stop.zone===focus?1:0)-(a.stop.zone===focus?1:0))||(kind==='attraction'?((b.stop.outdoor?1:0)-(a.stop.outdoor?1:0)):0));$(id).innerHTML=list.map(card).join('')||'<p class="empty">현재 조건에 맞는 후보가 없습니다. 시간·동선·이동 방식을 조정해보세요.</p>';}
 $('excluded').innerHTML=current.choices.filter(r=>!r.feasible).map(r=>`<p>${esc(r.stop.name)} · ${esc(r.reason)}</p>`).join('');
 $('timeline').innerHTML=`<div class="step"><strong>${clock(current.start)} · 출발</strong><p>${esc(lookup(state.origin).name)}</p></div>`+current.timeline.map((r,i)=>`<div class="step"><strong>${clock(r.visit)}–${clock(r.finish)} · ${esc(r.stop.name)}</strong><p>${r.policy?esc(r.policy.label)+' · ':''}이동 ${r.incoming}분 · 체류 ${r.stay}분 + 여유 ${r.buffer}분${r.wait?' · 대기 '+r.wait+'분':''}${r.policy?.rounds===2?' · 두 팀 식사·대기·교대 합계 '+r.policy.total+'분':''}</p><button class="secondary" type="button" data-remove="${i}">이 정차 빼기</button></div>`).join('')+`<div class="step"><strong>${Number.isFinite(current.eta)?clock(current.eta):'이동 불가'} · 목적지</strong><p>${esc(lookup(state.destination).name)} · 마지막 이동 ${Number.isFinite(current.direct)?current.direct+'분':'불가'}</p><p>마감 ${clock(current.end)}</p>${Number.isFinite(current.direct)?`<a class="fine" href="${route(current.from,lookup(state.destination),state.mode)}" target="_blank" rel="noopener">마지막 경로 확인</a>`:''}</div>`;
 $('save-status').textContent=saveState(storage,state)?'이 브라우저에 저장했어요.':'브라우저 저장 불가 · 현재 화면에서 계속 계획할 수 있어요.';
}
$('form').addEventListener('submit',e=>e.preventDefault());$('form').addEventListener('change',()=>{const next={...state};for(const f of fields)next[f]=['rain','stroller'].includes(f)?$(f).checked:$(f).value;state=next;render();});
$('reset').addEventListener('click',()=>{state={...state,selected:[]};render();});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.preset){state=normalize({preset:b.dataset.preset});fill();render();}if(b.dataset.add&&current.choices.some(r=>r.stop.id===b.dataset.add&&r.feasible)&&!current.error){state.selected.push(b.dataset.add);render();}if(b.dataset.remove!==undefined){state.selected.splice(Number(b.dataset.remove),1);render();}});
fill();render();
