import {lookup} from './engine.mjs?v=20261007-meal-modes-2';
export const CHECKED='2026-10-07';
export const EVIDENCE={
 shizenan:{official:'공식 점포 안내: 정원·개실·테이블, 휠체어 대응 가능, 60명 수용 안내. 점심 11–16:30 / 주문 마감 15:30. 평일 예약 코스는 4,500엔 이상, 주말은 5,000엔부터이며 별도 저가 런치 메뉴 없음.',officialUrl:'https://www.umenohana.co.jp/stores/detail/66',google:'오늘 Google 4.2 / 리뷰 514개 확인. 표본: 메인 거리에서 조금 떨어져 조용하고 정원 좋음(3개월 전), 친절한 설명(8개월 전), 정갈한 두부 가이세키·조용한 방(6개월 전). Google 입구 접근 불가 표시는 공식 휠체어 대응 안내와 상충합니다.',googleQuery:'梅の花 太宰府別荘自然庵',judgment:'예약·식사 예산이 괜찮다면 정원·조용한 분위기를 좋아하는 부부 점심으로 추천합니다. 식사는 100–120분 중 110분을 계획 가정으로 확보합니다. 가족 단체는 유모차 진입·자리·예약 조건을 반드시 문의하세요. 해당 점포를 방문한 커뮤니티 후기 표본은 확인하지 못했습니다.'},
 royalcafe:{official:'공식 오호리공원점: 1층, 총 152석(실내 90석), 예약 링크. 평일 11시 시작, 런치 11–15시. 안내된 10월 특별 휴무는 22·24일로 여행일과 다릅니다.',officialUrl:'https://www.royal-gardencafe.com/store-menu/ohoripark.html',google:'오늘 Google 4.0 / 리뷰 737개와 입구 접근 가능 표시 확인. 표본: 전망·분위기는 좋지만 가격·대기 부담(3개월 전), 산책 후 쉬기·빠른 식사 서비스 만족(8개월 전).',googleQuery:'ロイヤルガーデンカフェ 大濠公園',judgment:'오호리 산책 뒤 동선이 짧은 부부 점심 후보입니다. 오호리 지역 커뮤니티 여행기는 이 점포를 방문했다는 근거가 아닙니다. 가족 단체 동석·유모차 자리는 예약 때 문의하세요.'},
 bearfruits:{official:'공식 브랜드 점포 안내. 본점과 다른 점포의 편의시설 정보가 섞일 수 있어 기저귀대 등을 본점 시설로 확정하지 않습니다.',officialUrl:'https://bearfruits.jp/bearfruits',google:'오늘 Google 4.1 / 리뷰 1,393개 확인. 표본: 일찍 도착 권장·맛은 좋지만 소고기가 퍽퍽(3개월 전), 11:30 대기 없이 입장(5개월 전), 평일 12시 30분 대기·맛 호불호·어린이 카레 언급(3개월 전). 휠체어 입구 불가 표시.',googleQuery:'BEAR FRUITS 門司港',judgment:'카레혼포 대안이지만 가족 단체 자리·유모차 접근은 문의해야 합니다. 가족 함께 식사는 대기 30분·식사 90분 가정입니다. 나눠 동시 식사는 최소 70분·대기 30분, 교대는 두 팀 각각의 식사·대기·교대 10분을 합산합니다.'},
 motsu:{google:'오늘 정확한 하카타역앞점 Google 4.8 / 리뷰 24,119개 확인(조회 중 갱신). 휠체어 입구 없음으로 표시. 리뷰 본문은 보이지 않아 맛·대기 후기를 종합하지 못했습니다.',googleQuery:'楽天地 博多駅前店 0924518970',official:'공식 점포 정보: 178석과 예약 링크. 영업 17시–다음날 01시, 주문 마감 00:30. 개실·유모차 동석은 미확인.',officialUrl:'https://rakutenti.com/shop/hakata3/',judgment:'예약·단체 자리 가능성을 먼저 확인할 수 있는 저녁 후보. 공식 좌석 수만으로 일행 동석을 보장하지 않습니다.'},
 ohoripark:{google:'오늘 Google 4.5 / 리뷰 15,713개 확인. 표본: 한 시간 산책·쉬기 좋음(1개월 전), 맑은 날 풍경·반 바퀴만 걸어도 좋음(4개월 전), 카페 혼잡으로 포장 권장(8개월 전).',googleQuery:'Ohori Park Fukuoka',community:'2026년 6월 여행기는 호숫가 아침과 모모치·모지코·가라토를 느긋하게 방문한 경험을 소개합니다.',communityUrl:'https://www.reddit.com/r/FilipinoTravel/comments/1u8xykq/laidback_japan/',official:'공식 공원 안내에 호수 산책·공원 시설 소개.',officialUrl:'https://www.ohorikouen.jp/',judgment:'평탄한 호숫가를 짧게 걷는 자연 풍경 코스로 우선합니다. 유모차 이동 편의는 가족에 대한 판단이며, 이동·휴식 시간을 별도로 확보합니다.'},
 dazaifutemple:{official:'공식 FAQ에서 참배·방문 관련 안내 제공. 주변 거리·정원과 문화 코스로 계획.',officialUrl:'https://www.dazaifutenmangu.or.jp/en/plan/faq/',community:'2026년 2월 여행기는 접근길 모치의 점포별 호불호를 소개합니다. 줄이 길다고 맛을 보장하지 않습니다.',communityUrl:'https://www.reddit.com/r/JapanTravel/comments/1r6v9gg/northern_kyushu_1_week_trip_report_20262/',judgment:'작은 거리·정원을 좋아할 때 대안입니다. 왕복 이동이 길고 혼잡·돌바닥 구간은 아기띠를 보조로 사용합니다.'},
 katsu:{official:'고쿠라역앞점 공식 안내. 가족 단체 동석·유모차 공간은 확인하지 못했습니다.',officialUrl:'https://gyukatsu-kyotokatsugyu.com/store/kokuraekimae/',google:'오늘 Google 4.7 / 리뷰 5,005개 확인. 표본: 4인 테이블·아이 식기 제공(3개월 전), 점심 맛·직원 친절 만족(1개월 전), 맛 비추천(4개월 전). Google는 휠체어 입구 불가로 표시.',googleQuery:'牛カツ京都勝牛 小倉駅前店',judgment:'높은 평점만으로 가족 단체의 첫 추천으로 고르지 않습니다. 분산 착석·유모차 통로 가능성을 문의하고, 시설 식당가를 대안으로 둡니다.'},
 unagi:{official:'공식 층별 안내: 2층은 장벽 없는 접근, 유모차로 좌석 접근 가능. 6인용 테이블 2개 안내. 일반 좌석 예약은 최대 4명이며, 8명 가능한 개실은 별도 요금 10%가 있습니다. 3층 기저귀 교환대 안내.',officialUrl:'https://yoshizukaunagi.com/room/',google:'오늘 Google 4.4 / 리뷰 9,398개 확인. 후기 표본: 평일 17시 대기 없이 입장(4개월 전), 개점 전 09:30부터 기다린 뒤 음식까지 약 30분(3개월 전), 소스가 짜다는 평가(1개월 전).',googleQuery:'吉塚うなぎ屋',judgment:'첫날 부부 저녁에는 적합합니다. 가족 단체는 개실·유아 자리·유모차 공간을 먼저 문의하세요. 대기와 맛은 방문 시각·취향에 따라 달라집니다.'},
 curry:{official:'공식 점포 페이지는 2층 주소. Google 접근성 정보는 1층·휠체어 입구 없음으로 표시되어 정보가 상충합니다. 층수·계단·유모차 보관은 직접 확인해야 합니다.',officialUrl:'https://www.curry-honpo.com/mojikou-retro.html',google:'오늘 Google 4.4 / 리뷰 2,032개 확인. 후기 표본: 목요일 15시 약 10분 대기(5개월 전), 아이 동반 맛 만족과 긴 대기(2개월 전), 기다릴 만큼인지 의문이라는 맛 평가(2개월 전).',googleQuery:'伽哩本舗 門司港レトロ店',community:'2026년 2월 여행기: 늦은 점심 야키카레에 만족, 모지코를 작은 동네로 묘사. 가라토는 점포별 맛 차이·혼잡을 경험했다고 보고.',communityUrl:'https://www.reddit.com/r/JapanTravel/comments/1r6v9gg/northern_kyushu_1_week_trip_report_20262/',judgment:'지역 대표 음식 후보이지만 단체 동시 착석·유아 자리·층수는 미확인입니다. 아기띠로 계단 접근을 보조할 수 있어도 유모차 보관은 별도 문의. 가족 함께 식사는 90분 + 대기 30분 가정. 나눠 동시 식사는 최소 70분 + 대기 30분, 교대는 두 팀 각각의 식사·대기와 교대 10분을 합산합니다. 분산 착석도 입장·유모차 공간을 보장하지 않습니다.'},
 hanamidori:{google:'오늘 정확한 하카타역앞점 Google 4.2 / 리뷰 1,565개와 휠체어 입구 가능 표시 확인. 리뷰 본문은 보이지 않아 후기 내용은 종합하지 못했습니다.',googleQuery:'博多華味鳥 博多駅前店 3-23-17',community:'다벨로그 표본: 2026년 6월 혼자 19:30 방문·대기 없이 카운터 이용, 2025년 11월 조용한 분위기·점심 가라아게 추천. 혼자 방문한 경험을 단체에 일반화하지 않습니다.',communityUrl:'https://tabelog.com/fukuoka/A4001/A400101/40003174/',official:'하카타역앞점 공식 안내: 106석·개실·온라인 예약 안내. 점심 11:30–15:00(주문 마감 14시), 저녁 17시부터. 유모차 자리·단체 빈자리·유아 자리는 미확인.',officialUrl:'https://www.hanamidori.net/stores/0924321801/',judgment:'가족 단체는 좌석·개실·예약 가능 여부를 확인하기 쉬운 후보입니다. 부부 저녁에도 적합하지만 실제 자리 확보·유모차 수용이 확인된 예약은 아닙니다.'},
 retro:{official:'항구 중심의 관광 동네이며 시설별 운영·접근성은 각각 확인해야 합니다.',officialUrl:'https://www.mojiko.info/',community:'2026년 2월 여행자는 모지코를 작은 동네로 소개하며 늦은 점심을 즐겼습니다. 한 방문자의 여행 경험입니다.',communityUrl:'https://www.reddit.com/r/JapanTravel/comments/1r6v9gg/northern_kyushu_1_week_trip_report_20262/',judgment:'평탄한 항구 산책을 우선하고, 혼잡한 구간은 유모차와 아기띠를 병행하는 판단입니다.'},
 market:{google:'오늘 Google 4.1 / 리뷰 25,887개 확인. 표본: 점포별 초밥 종류·맛 차이(2개월 전), 토요일 인파(4개월 전), 주말 11시 이후 혼잡해 일찍 방문 권장(4개월 전).',googleQuery:'唐戸市場 下関',official:'먹거리 행사는 금·토 10–15시, 일·공휴일 07–15시. 개최일은 공식 달력 확인.',officialUrl:'https://www.karatoichiba.com/bakangai/',community:'2026년 2월 여행기에서는 점포별 맛 차이와 혼잡을 경험했습니다.',communityUrl:'https://www.reddit.com/r/JapanTravel/comments/1r6v9gg/northern_kyushu_1_week_trip_report_20262/',judgment:'시장 점심을 코스에 포함하되 가족 단체가 함께 앉을 수 있는지 보장하지 않습니다. 혼잡하면 아기띠를 보조로 사용하고 가까운 항구 산책으로 줄이세요.'}
};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function evidenceHTML(ids){const unique=[...new Set(ids.filter(Boolean))];let unresearched=false;const blocks=unique.map(id=>{const e=EVIDENCE[id];if(!e){if(unresearched)return '';unresearched=true;return '<p><b>리뷰 종합 전 · 조건 확인용 대안</b> — 이 장소의 Google 후기·커뮤니티를 아직 종합하지 않았습니다. 영업·좌석·유모차 접근을 확인하세요.</p>';}return `<div class="evidence-block"><h4>${escape(lookup(id)?.name||id)}</h4>${e.official?`<p><b>공식 사실</b> · ${escape(e.official)} <a href="${e.officialUrl}" target="_blank" rel="noopener">공식 출처</a></p>`:''}${e.google?`<p><b>Google 확인 후기 표본</b> · ${escape(e.google)} <a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(e.googleQuery)}" target="_blank" rel="noopener">Google 장소·후기</a></p>`:'<p><b>Google 후기</b> · 추가 종합 전입니다.</p>'}${e.community?`<p><b>커뮤니티</b> · ${escape(e.community)} <a href="${e.communityUrl}" target="_blank" rel="noopener">여행기 원문</a></p>`:'<p><b>커뮤니티</b> · 확인한 표본 없음.</p>'}<p><b>우리 가족에 대한 판단</b> · ${escape(e.judgment)}</p></div>`;});return `<details class="recommend-evidence"><summary>추천 근거 · 공식 / 후기 / 가족 적합성</summary><p class="fine">확인일 ${CHECKED} · 일부 후기 표본이며 전체 리뷰의 합의를 뜻하지 않습니다. 공식 사실과 경험·추론을 나눠 표시합니다.</p>${blocks.join('')}</details>`;}
