import {DAYS,DAYINFO,COURSES,conditionInput,evaluate,cases,fallback,recommend,selectedResult,resolve} from './scenarios.mjs?v=20261008-daily-plan-1';
import {DINING_DETAILS} from './dining-details.mjs?v=20261008-daily-plan-1';
import {detailedTimeline,timelinePins,embedMap} from './timeline-view.mjs?v=20261008-daily-plan-1';
import {hourEvents,defaultViewTime,daySpan,loadDaily,DAILY_STORAGE_KEY,inlineGoogle} from './daily-view.mjs?v=20261008-daily-plan-1';
import {clock,time,route,maps} from './engine.mjs?v=20261008-daily-plan-1';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage;try{storage=window.localStorage;}catch{storage=null;}let state=loadDaily(storage),current,pins=[],view='day',viewTime=null;
const shortName=p=>({airport:'국제선',hotel:'하카타 숙소',kf1:'모지 숙소',hakata:'하카타역'})[p.id]||p.name;
function risk(r){if(!r.feasible)return r.problems.join(' · ');if(r.day==='12')return `국제선 ${clock(r.finish)} 도착 · 15시까지 ${900-r.finish}분 여유${900-r.finish<15?' · 추가 대기 시 마감 위험':''}`;if(r.day==='10')return `KF1 체크인 ${clock(r.finish-30)}–${clock(r.finish)} · 16시 이후`;if(r.day==='09')return '부부 낮 일정 후 가족 21시 체크인 · 22시 한계';return `숙소 ${clock(r.finish)} 복귀 · ${r.day==='08'?'21':'18'}시까지 여유 ${((r.day==='08'?1260:1080)-r.finish)}분`;}
function persist(){try{storage.setItem(DAILY_STORAGE_KEY,JSON.stringify(state));$('save-status').textContent='이 브라우저에 하루별 선택을 저장했어요.';}catch{$('save-status').textContent='저장 불가 · 현재 화면에서 계속 계획할 수 있어요.';}}
function timeRange(t){return t.start===t.end?clock(t.start):`${clock(t.start)}–${clock(t.end)}`;}
function link(p,label){return `<a href="${maps(p)}" target="_blank" rel="noopener">${esc(label||p.name)}</a>`;}
function links(t){if(t.from)return `${link(t.from,'출발 장소')} · ${link(t.to,'도착 장소')}${t.flight?'':` · <a class="route-link" href="${route(t.from,t.to,state.conditions.mode)}" target="_blank" rel="noopener">이동 경로 ↗</a>`}`;return t.place?link(t.place,'장소 지도 ↗'):'';}
function whereLine(r){const groups=new Map();for(const t of r.timeline){if(t.flight)continue;const stream=t.stream||'일행',list=groups.get(stream)||[];for(const p of t.from?[t.from,t.to]:t.place?[t.place]:[]){const n=shortName(p);if(list.at(-1)!==n)list.push(n);}groups.set(stream,list);}return [...groups].filter(([,list])=>list.length).map(([stream,list])=>(r.day==='09'?stream+': ':'')+list.join(' → ')).join(' · ');}
function destinationTime(r){return r.day==='08'?'숙소 '+clock(r.finish)+' 복귀':r.day==='09'?'가족 체크인 '+clock(r.finish)+' 완료':r.day==='10'?'KF1 체크인 '+clock(r.finish)+' 완료':r.day==='11'?'숙소 '+clock(r.finish)+' 복귀':'공항 '+clock(r.finish)+' 도착';}
function mealResult(id){return evaluate(state.day,current.course,state.conditions,id);}
function mealPicker(t){const options=current.course.mealIds||[],d=DINING_DETAILS[t.place.id]||{},photo=d.photos?.[0],g=d.google||{},menu=d.menu||{};return `<details class="inline-meal"><summary>식사 사진·메뉴 / 바꾸기</summary><div class="meal-preview">${photo?`<figure><img src="${esc(photo.url)}" alt="${esc(photo.alt)}" loading="lazy"><figcaption>${esc(photo.credit)} · <a href="${esc(photo.source)}" target="_blank" rel="noopener">사진 출처</a></figcaption></figure>`:''}<div><p><b>${esc(menu.name||t.place.cuisine||'식사 선택지')}</b></p><p>${(menu.items||[]).slice(0,3).map(esc).join(' · ')}</p>${inlineGoogle(g)}<p class="fine">${esc(menu.basis||'영업·대기·유모차 자리 확인 필요')}</p><a class="fine" href="${esc(g.url||maps(t.place))}" target="_blank" rel="noopener">Google 장소·후기</a></div></div>${options.length?`<label>같은 동선의 다른 식사<select class="selected-meal">${options.map(id=>{const r=mealResult(id);return `<option value="${id}" ${id===current.meal?'selected':''} ${r.feasible?'':'disabled'}>${esc(resolve(id).name)} · ${r.feasible?destinationTime(r):r.problems.join(' · ')}</option>`;}).join('')}</select></label>`:''}<p class="fine">방식별 대기·식사 시간을 포함합니다. 모두 식사를 마쳐야 다음 이동을 시작합니다.</p></details>`;}
function eventCard(t,index){const quiet=!t.from&&!t.place&&/휴식|대기|준비|입국/.test(t.name);const firstMeal=current.timeline.find(x=>x.meal&&x.place)?.place?.id===t.place?.id&&(!t.mealPolicy||t.mealPolicy.rounds===1||t.name.includes('팀 1'));return `<article class="event-card ${t.mandatory?'fixed-event':''} ${quiet?'quiet-event':''}"><div class="event-time"><time>${timeRange(t)}</time>${t.stream?'<span>'+esc(t.stream)+'</span>':''}</div><div class="event-body"><span class="event-kind">${t.mandatory?'기본 일정':t.conditional?'필요하면':'추천 정차'}${t.travel?' · '+t.travel+'분 이동':''}</span><h3>${esc(t.name)}</h3>${t.detail?`<p class="event-reason">${esc(t.detail)}</p>`:''}<div class="event-links">${links(t)}</div>${t.guide?`<details class="transport-detail"><summary>${esc(t.guide.label)} · 이용 방법</summary><ol>${t.guide.steps.map(x=>'<li>'+esc(x)+'</li>').join('')}</ol><p class="fine">${esc(t.guide.note)}</p><p class="fine">${t.guide.sources.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.label)}</a>`).join(' · ')}</p></details>`:''}${t.meal&&firstMeal?mealPicker(t):''}</div></article>`;}
function eventList(list){return list.map(eventCard).join('');}
function drawTimeline(){const events=detailedTimeline(current);if(view==='day'){$('selected-timeline').innerHTML=eventList(events);$('view-caption').textContent='하루 전체 계획 · 실제 위치나 실시간 운행을 추적하지 않습니다.';}else{const slice=hourEvents(events,time(viewTime));$('selected-timeline').innerHTML=`<div class="hour-focus"><h3>${clock(slice.at)} 기준 · 지금 계획</h3>${slice.current.length?eventList(slice.current):'<p class="fine">이 시각에 진행 중인 일정이 없습니다.</p>'}${slice.next.length?'<h3>다음 이동·정차</h3>'+eventList(slice.next):'<p class="fine">이 시각 이후 새 일정이 없습니다.</p>'}</div>${slice.earlier.length?`<details class="daily-fold"><summary>이전 시간표 · ${slice.earlier.length}개</summary>${eventList(slice.earlier)}</details>`:''}${slice.later.length?`<details class="daily-fold"><summary>이후 시간표 · ${slice.later.length}개</summary>${eventList(slice.later)}</details>`:''}`;$('view-caption').textContent='선택 시간 기준 계획 · 실제 위치나 실시간 교통을 추적하지 않습니다.';}$('day-view').setAttribute('aria-pressed',view==='day');$('hour-view').setAttribute('aria-pressed',view==='hour');$('view-time-label').hidden=view!=='hour';$('view-time').value=viewTime;}
function compactCourse(r,best){const selected=r.course.id===current.course.id,delta=r.finish-current.finish;return `<article class="alternative-row"><div><h3>${esc(r.course.title)} ${selected?'<small>선택 중</small>':best?'<small>추천</small>':''}</h3><p>${esc(r.course.why)}</p><p class="fine">${r.feasible?`${destinationTime(r)} · 현재보다 ${delta===0?'같은 시각':Math.abs(delta)+'분 '+(delta>0?'늦게':'일찍')}`:esc(r.problems.join(' · '))}</p></div><button class="secondary" data-course="${r.course.id}" ${!r.feasible?'disabled':''}>${selected?'선택 중':'이 코스로'}</button></article>`;}
function drawMap(){pins=timelinePins(detailedTimeline(current));$('map-pins').innerHTML=pins.map((p,i)=>`<li><button class="secondary" data-pin="${i}">${p.number} · ${esc(p.name)}</button><span class="fine">${esc(p.stream)} · ${p.transfer?'구간 내 환승 · 개별 시각 미정':clock(p.at)}</span> ${link(p,'Google 지도 ↗')}</li>`).join('');if(pins.length)showMap(0);}
function showMap(index){const p=pins[index];if(!p)return;$('map-title').textContent=p.number+' · '+p.name;$('place-map').src=embedMap(p);$('place-map').title=p.name+' Google 지도';$('map-external').href=p.url;}
function render(){const changed=[];for(const day of DAYS){const r=selectedResult(state,day);if(state.choices[day]&&state.choices[day].course!==r.course.id)changed.push('10/'+day);state.choices[day]={course:r.course.id,meal:r.meal};}current=selectedResult(state,state.day);viewTime=viewTime||defaultViewTime(state.day,current.timeline);const span=daySpan(current.timeline),best=recommend(state.day,state.conditions);$('days').innerHTML=DAYS.map((d,i)=>`<button data-day="${d}" class="${d===state.day?'active':''}" aria-pressed="${d===state.day}"><b>10/${Number(d)}</b><span>${['목','금','토','일','월'][i]} · ${i<2?'부부':'가족'}</span></button>`).join('');$('party').textContent='10/'+state.day+' · '+DAYINFO[state.day].party+' · '+clock(span.start)+'–'+clock(span.end);$('selected-title').textContent=current.course.title;$('daily-route').textContent=whereLine(current);$('day-risk').textContent=risk(current);$('daynote').textContent=DAYINFO[state.day].note;$('notice').innerHTML=(!current.feasible?`<p class="error">${esc(current.problems.join(' · '))}</p>`:'')+(changed.length?`<p class="note">조건에 맞춰 ${changed.join(', ')} 코스를 조정했습니다.</p>`:'');for(const f of ['mode','mealMode','delay','mealWait'])$(f).value=state.conditions[f];$('relaxed').checked=state.conditions.relaxed;drawTimeline();drawMap();$('courses').innerHTML=[...cases(state.day,state.conditions),fallback(state.day,state.conditions)].map(r=>compactCourse(r,r.course.id===best.course.id)).join('');$('overview').innerHTML=DAYS.map(d=>{const r=selectedResult(state,d);return `<div class="overview-row"><b>10/${d}</b><div><p>${esc(r.course.title)}</p><span class="fine">${esc(risk(r))}</span></div><button data-day="${d}" class="secondary">이 날 보기</button></div>`;}).join('');persist();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.day){state.day=b.dataset.day;viewTime=null;render();}if(b.dataset.pin!==undefined)showMap(Number(b.dataset.pin));if(b.dataset.course){const c=COURSES[state.day].find(x=>x.id===b.dataset.course);state.choices[state.day]={course:b.dataset.course,meal:c?.mealIds?.[0]};render();}});
for(const f of ['relaxed','mode','delay','mealWait','mealMode'])$(f).addEventListener('change',()=>{state.conditions[f]=conditionInput(f,f==='relaxed'?$(f).checked:$(f).value);render();});
document.addEventListener('change',e=>{if(e.target.classList.contains('selected-meal')){const wanted=e.target.value;state.choices[state.day].meal=wanted;render();if(current.meal!==wanted)$('notice').innerHTML+='<p class="note">식사·대기를 포함하면 마감에 맞지 않아 가능한 식사로 조정했습니다.</p>';}});
$('day-view').addEventListener('click',()=>{view='day';drawTimeline();});$('hour-view').addEventListener('click',()=>{view='hour';drawTimeline();});$('view-time').addEventListener('change',()=>{viewTime=$('view-time').value;drawTimeline();});$('reset').addEventListener('click',()=>{delete state.choices[state.day];render();});render();
