import {DAYS,DAYINFO,COURSES,conditionInput,evaluate,cases,fallback,recommend,loadV2,selectedResult,locationMap,resolve} from './scenarios.mjs?v=20261007-dining-guide-1';
import {MEAL_MODES,mealPolicy} from './meal-policy.mjs?v=20261007-dining-guide-1';
import {evidenceHTML} from './evidence.mjs?v=20261007-dining-guide-1';
import {detailedTimeline,timelinePins,embedMap} from './timeline-view.mjs?v=20261007-dining-guide-1';
import {clock,route,maps} from './engine.mjs?v=20261007-dining-guide-1';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage;try{storage=window.localStorage;}catch{storage=null;}let state=loadV2(storage);let current;
const fixedLabels={'08':['13:40 국제선 도착','15:10 입국 완료','숙소 체크인 먼저','21시 숙소 복귀'],'09':['09시 부부 출발','18시 하카타 복귀','18:30 가족 도착','19:45 입국 완료','22시 체크인 한계'],'10':['10시 체크아웃','13시 짐 맡기기 가능','16시부터 KF1 체크인'],'11':['09시 KF1 출발','18시 KF1 복귀'],'12':['10시 출발 권장','11시 이후 짐 보관 불가','15시 국제선 도착 필수','18시 출발 → 19:45 인천']};
function persist(){try{storage.setItem('fukuoka-courses-v2',JSON.stringify(state));$('save-status').textContent='5일의 선택을 이 브라우저에 저장했어요.';}catch{$('save-status').textContent='저장이 불가능한 브라우저입니다. 현재 화면에서 계속 선택할 수 있어요.';}}
function risk(r){if(!r.feasible)return r.problems.join(' · ');if(r.day==='12')return `${900-r.finish<15?'여유 매우 짧음 · 추가 대기 시 마감 초과 위험 · ':''}국제선 ${clock(r.finish)} 도착 · 15시까지 ${900-r.finish}분 여유`;if(r.day==='08')return `숙소 ${clock(r.finish)} 복귀 · 21시까지 ${1260-r.finish}분 여유`;if(r.day==='10')return `KF1 체크인 ${clock(r.finish-30)}–${clock(r.finish)} · 16시 이후`;if(r.day==='09')return '부부 낮 일정 후 가족 체크인 21시 · 22시 한계';return `KF1 ${clock(r.finish)} 복귀 · 18시까지 ${1080-r.finish}분 여유`;}
function courseCard(r,best){if(r.day==='12'&&900-r.finish<15)best=false;const selected=r.course.id===current.course.id;const stops=r.timeline.filter(t=>!t.mandatory&&t.place).map(t=>t.name);const meal=r.meal?resolve(r.meal):null;return `<article class="coursecard ${selected?'chosen':''} ${!r.feasible?'unavailable':''}"><div class="coursehead"><span class="tag ${best?'recommended':''}">${best?'추천 #1':r.course.id==='direct'?'필수 이동·휴식':r.course.rain?'휴식·실내 대안':'다른 선택'}</span>${selected?'<span class="fine">✓ 지금 선택한 코스</span>':''}</div><h3>${esc(r.course.title)}</h3><p class="muted">${esc(r.course.why)}</p><div class="route-text">${stops.map(esc).join(' → ')||'숙소·공항 필수 이동 + 휴식'}</div>${meal?`<p class="fine">기본 식사: ${esc(meal.name)} · ${esc(meal.cuisine)}${meal.facility?' (시설·검색 선택지)':''}</p><p class="fine">${esc(mealPolicy({family:!['08','09'].includes(r.day),mode:state.conditions.mealMode,duration:meal.stay,facility:meal.facility}).label)} · ${esc(mealPolicy({family:!['08','09'].includes(r.day),mode:state.conditions.mealMode,duration:meal.stay,facility:meal.facility}).explanation)}</p>`:''}${r.course.carry?'<p class="risk">체크인 전까지 짐 동반 · 유모차와 짐 이동 고려</p>':''}<p class="risk">${esc(risk(r))}</p>${courseSummary(r)}${evidenceHTML([r.meal,...(r.course.steps||[]).map(x=>x.id)])}<div class="coursefoot"><span class="fine">${r.feasible?'시간 계산 가능 · 실제 영업 확인 필요':'조건 변경이 필요합니다'}</span><button data-course="${r.course.id}" ${!r.feasible?'disabled':''}>${selected?'선택한 코스':'이 코스 선택'}</button></div></article>`;}
function mealArrival(r){return r.feasible?(r.day==='12'?'국제선 ':r.day==='10'?'체크인 완료 ':'숙소 복귀 ')+clock(r.finish)+(r.day==='12'&&900-r.finish<15?' · 여유 매우 짧음':''):'불가: '+r.problems.join(' · ');}
function mealComparison(r){if(['08','09'].includes(r.day))return '<p class="fine">부부 낮 식사는 식사 방식 변경의 영향을 받지 않습니다.</p>';return `<details><summary>식사 방식별 도착 시간 비교</summary>${r.course.mealIds.map(id=>`<p><b>${esc(resolve(id).name)}</b></p>${Object.entries(MEAL_MODES).map(([mode,label])=>{const trial=evaluate(r.day,r.course,{...state.conditions,mealMode:mode},id);return `<p class="fine">${esc(label)}: ${esc(mealArrival(trial))}</p>`;}).join('')}`).join('')}</details>`;}
function timeRange(t){return t.start===t.end?clock(t.start):`${clock(t.start)}–${clock(t.end)}`;}
function placeLink(p,label=p.name){return `<a href="${maps(p)}" target="_blank" rel="noopener">${esc(label)}</a>`;}
function eventLinks(t){if(t.from){return `${placeLink(t.from,'출발 핀')} · ${placeLink(t.to,'도착 핀')}${t.flight?'':` · <a href="${route(t.from,t.to,state.conditions.mode)}" target="_blank" rel="noopener">이 구간 Google 경로</a>`}`;}return t.place?placeLink(t.place,'Google 지도 핀'):'';}
function courseSummary(r){return `<div class="course-summary" aria-label="이 코스 전체 시간표">${r.timeline.map(t=>`<div class="summary-event"><time>${timeRange(t)}</time><div>${t.stream?`<span class="fine">${esc(t.stream)} · </span>`:''}<span>${esc(t.name)}</span>${t.travel?`<span class="fine"> · ${t.travel}분${t.flight?' 항공':' 이동 가정'}</span>`:''}${eventLinks(t)?'<div class="summary-links">'+eventLinks(t)+'</div>':''}</div></div>`).join('')}</div>`;}
function timeline(r){return detailedTimeline(r).map(t=>`<div class="schedule-step ${t.mandatory?'mandatory':'optional'}"><div class="event-time"><time>${timeRange(t)}</time><span class="badge-small">${t.stream?esc(t.stream)+' · ':''}${t.mandatory?'필수':t.conditional?'조건부':'선택'}</span></div><div class="event-body"><strong>${esc(t.name)}</strong>${t.travel?`<p>${t.travel}분 ${t.flight?'항공 이동 · 예정 시각':'구간 이동 가정'}</p>`:''}${t.detail?'<p class="muted">'+esc(t.detail)+'</p>':''}${t.guide?`<p><b>${esc(t.guide.label)}</b></p><ol class="transport-steps">${t.guide.steps.map(x=>'<li>'+esc(x)+'</li>').join('')}</ol><p class="fine">${esc(t.guide.note)} 공식 안내 확인: 2026-10-07.</p><div class="links">${t.guide.sources.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.label)}</a>`).join('')}</div>`:''}<div class="links">${eventLinks(t)}${t.place?.source?` · <a href="${esc(t.place.source)}" target="_blank" rel="noopener">공식 안내</a>`:''}</div></div></div>`).join('');}
let pins=[];
function drawMap(r){pins=timelinePins(detailedTimeline(r));$('map-pins').innerHTML=pins.map(p=>`<li><button class="secondary" data-pin="${p.number-1}">${p.number} · ${esc(p.name)}</button><span class="fine">${esc(p.stream)} · ${p.transfer?timeRange({start:p.range[0],end:p.range[1]})+' 구간 안 환승 · 개별 시각 미정':clock(p.at)}</span> ${placeLink(p,'Google 지도 ↗')}</li>`).join('');if(pins.length)showMap(0);}
function showMap(index){const p=pins[index];if(!p)return;$('map-title').textContent=p.number+' · '+p.name;$('place-map').src=embedMap(p);$('place-map').title=p.name+' Google 지도';$('map-external').href=p.url;}
function render(){const changed=[];for(const day of DAYS){const r=selectedResult(state,day);const old=state.choices[day];if(old&&old.course!==r.course.id)changed.push('10/'+day);state.choices[day]={course:r.course.id,meal:r.meal};}current=selectedResult(state,state.day);const day=state.day,best=recommend(day,state.conditions),all=[...cases(day,state.conditions),fallback(day,state.conditions)];all.sort((a,b)=>(b.course.id===best.course.id?1:0)-(a.course.id===best.course.id?1:0));
 $('days').innerHTML=DAYS.map(d=>`<button data-day="${d}" class="${day===d?'active':''}" aria-pressed="${day===d}">10/${d} · ${['08','09'].includes(d)?'부부':'가족'}</button>`).join('');for(const f of ['relaxed'])$(f).checked=state.conditions[f];$('mode').value=state.conditions.mode;$('delay').value=state.conditions.delay;$('mealWait').value=state.conditions.mealWait;$('mealMode').value=state.conditions.mealMode;
 $('party').textContent=DAYINFO[day].party;$('daytitle').textContent='10/'+day+' · '+DAYINFO[day].title;$('daynote').textContent=DAYINFO[day].note;$('anchors').innerHTML=fixedLabels[day].map((x,i)=>`<span><b>필수 ${String(i+1).padStart(2,'0')}</b>${esc(x)}</span>`).join('');
 $('notice').innerHTML=(!current.feasible?`<p class="error">${esc(current.problems.join(' · '))} · 지연을 줄이거나 이동 조건을 확인하세요. 필수 일정은 그대로 표시합니다.</p>`:'')+(changed.length?`<p class="note">조건에 맞춰 ${changed.join(', ')} 선택을 가능한 추천으로 조정했습니다.</p>`:'');
 $('courses').innerHTML=all.map(r=>courseCard(r.course.id===current.course.id?current:r,r.course.id===best.course.id)).join('');$('selected-title').textContent=current.course.title;$('selected-timeline').innerHTML=timeline(current);drawMap(current);
 $('meal-picker').innerHTML=current.course.mealIds?.length?`<div class="meal-picker"><label for="selected-meal">이 코스의 식사 바꾸기<select id="selected-meal">${current.course.mealIds.map(id=>`<option value="${id}" ${id===current.meal?'selected':''} ${evaluate(state.day,current.course,state.conditions,id).feasible?'':'disabled'}>${esc(resolve(id).name)} · ${esc(resolve(id).cuisine)} · ${esc(mealArrival(evaluate(state.day,current.course,state.conditions,id)))}</option>`).join('')}</select></label><p>같은 식사 지역의 선택지입니다. 바꾸면 이동 시간·도착 시간을 다시 계산합니다. 영업·대기는 별도 확인.</p>${mealComparison(current)}${evidenceHTML([current.meal])}</div>`:'';
 $('overview').innerHTML=DAYS.map(d=>{const r=selectedResult(state,d);return `<div class="overview-row"><b>10/${d}</b><div><p>${esc(r.course.title)}</p><span class="fine">${esc(risk(r))}</span></div><button data-day="${d}" class="secondary">${d===day?'보고 있어요':'이 날 보기'}</button></div>`;}).join('');persist();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.pin!==undefined){showMap(Number(b.dataset.pin));}if(b.dataset.day){state.day=b.dataset.day;render();}if(b.dataset.course){const c=COURSES[state.day].find(c=>c.id===b.dataset.course);state.choices[state.day]={course:b.dataset.course,meal:c?.mealIds?.[0]};render();}});
for(const f of ['relaxed','mode','delay','mealWait','mealMode'])$(f).addEventListener('change',()=>{state.conditions[f]=conditionInput(f,f==='relaxed'?$(f).checked:$(f).value);render();});
document.addEventListener('change',e=>{if(e.target.id==='selected-meal'){const wanted=e.target.value;state.choices[state.day].meal=wanted;render();if(current.meal!==wanted){$('notice').innerHTML+='<p class="note">바꾼 식사는 단체 식사·대기 시간을 포함하면 마감에 맞지 않아, 가능한 식사 또는 직행 대안으로 조정했습니다.</p>';}}});
$('reset').addEventListener('click',()=>{delete state.choices[state.day];render();});render();
